const json = `{
  "response": {
    "body": {
      "totalCount": 40,
      "items": [
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "30",
          "khaiGrade": null,
          "pm25Value": "19",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.024",
          "stationName": "중구",
          "pm10Grade": null,
          "o3Value": "0.033"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "한강대로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "27",
          "khaiGrade": null,
          "pm25Value": "12",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.019",
          "stationName": "종로구",
          "pm10Grade": null,
          "o3Value": "0.036"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "청계천로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "종로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.004",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "25",
          "khaiGrade": null,
          "pm25Value": "17",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.012",
          "stationName": "용산구",
          "pm10Grade": null,
          "o3Value": "0.043"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "29",
          "khaiGrade": null,
          "pm25Value": "17",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.009",
          "stationName": "광진구",
          "pm10Grade": null,
          "o3Value": "0.037"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.002",
          "coValue": "0.2",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "27",
          "khaiGrade": null,
          "pm25Value": "9",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.013",
          "stationName": "성동구",
          "pm10Grade": null,
          "o3Value": "0.043"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "강변북로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "중랑구",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.002",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "25",
          "khaiGrade": null,
          "pm25Value": "16",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.012",
          "stationName": "동대문구",
          "pm10Grade": null,
          "o3Value": "0.047"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "홍릉로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "32",
          "khaiGrade": null,
          "pm25Value": "13",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.015",
          "stationName": "성북구",
          "pm10Grade": null,
          "o3Value": "0.040"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "정릉로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.004",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "24",
          "khaiGrade": null,
          "pm25Value": "8",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.009",
          "stationName": "도봉구",
          "pm10Grade": null,
          "o3Value": "0.035"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.2",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "22",
          "khaiGrade": null,
          "pm25Value": "11",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.011",
          "stationName": "은평구",
          "pm10Grade": null,
          "o3Value": "0.037"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.004",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "1",
          "pm10Value": "25",
          "khaiGrade": null,
          "pm25Value": "12",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.007",
          "stationName": "서대문구",
          "pm10Grade": null,
          "o3Value": "0.029"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "25",
          "khaiGrade": null,
          "pm25Value": "17",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.012",
          "stationName": "마포구",
          "pm10Grade": null,
          "o3Value": "0.039"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "신촌로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "27",
          "khaiGrade": null,
          "pm25Value": "13",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.010",
          "stationName": "강서구",
          "pm10Grade": null,
          "o3Value": "0.043"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "공항대로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "26",
          "khaiGrade": null,
          "pm25Value": "7",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.007",
          "stationName": "구로구",
          "pm10Grade": null,
          "o3Value": "0.042"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.004",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "28",
          "khaiGrade": null,
          "pm25Value": "15",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.011",
          "stationName": "영등포구",
          "pm10Grade": null,
          "o3Value": "0.039"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "영등포로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.004",
          "coValue": "0.2",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "28",
          "khaiGrade": null,
          "pm25Value": "14",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.009",
          "stationName": "동작구",
          "pm10Grade": null,
          "o3Value": "0.040"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "동작대로 중앙차로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.004",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "34",
          "khaiGrade": null,
          "pm25Value": "17",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.009",
          "stationName": "관악구",
          "pm10Grade": null,
          "o3Value": "0.036"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.004",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "26",
          "khaiGrade": null,
          "pm25Value": "12",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.014",
          "stationName": "강남구",
          "pm10Grade": null,
          "o3Value": "0.041"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "19",
          "khaiGrade": null,
          "pm25Value": "6",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.013",
          "stationName": "서초구",
          "pm10Grade": null,
          "o3Value": "0.034"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "도산대로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "강남대로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "31",
          "khaiGrade": null,
          "pm25Value": "11",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.014",
          "stationName": "송파구",
          "pm10Grade": null,
          "o3Value": "0.042"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.2",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "25",
          "khaiGrade": null,
          "pm25Value": "14",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.005",
          "stationName": "강동구",
          "pm10Grade": null,
          "o3Value": "0.038"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "천호대로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.2",
          "pm25Flag": "장비점검",
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "31",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.012",
          "stationName": "금천구",
          "pm10Grade": null,
          "o3Value": "0.037"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "시흥대로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "30",
          "khaiGrade": null,
          "pm25Value": "17",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.014",
          "stationName": "강북구",
          "pm10Grade": null,
          "o3Value": "0.040"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.002",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "29",
          "khaiGrade": null,
          "pm25Value": "14",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.009",
          "stationName": "양천구",
          "pm10Grade": null,
          "o3Value": "0.039"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": "장비점검",
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "24",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": null,
          "so2Flag": null,
          "dataTime": "2022-09-16 13:00",
          "coGrade": "1",
          "no2Value": "0.010",
          "stationName": "노원구",
          "pm10Grade": null,
          "o3Value": "0.041"
        },
        {
          "so2Grade": null,
          "coFlag": "자료이상",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "자료이상",
          "pm10Flag": "자료이상",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "자료이상",
          "no2Grade": null,
          "o3Flag": "자료이상",
          "pm25Grade": null,
          "so2Flag": "자료이상",
          "dataTime": "2022-09-16 13:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "화랑로",
          "pm10Grade": null,
          "o3Value": "-"
        }
      ],
      "pageNo": 1,
      "numOfRows": 100
    },
    "header": {
      "resultMsg": "NORMAL_CODE",
      "resultCode": "00"
    }
  }
}`;

function findTarget(input) {
  const parsedData = JSON.parse(input.data);
  stdPath = input.stdPath.split(".");
  findTargetOnlyOne(parsedData, stdPath, input.stdValue);
}

function findTargetOnlyOne(data, path, stdValue) {
  key = path.shift();
  targetPath.push(key);
  if (key === undefined) {
    targetPath.pop();
    return data === stdValue;
  }

  try {
    if (data[key] === undefined) {
      targetArr.push(path.length ? `Invalid Key : ${key}` : undefined);
      return;
    }
    if (data[key] instanceof Array) {
      for (let item of data[key]) {
        const targetsArr = [];
        if (findTargetOnlyOne(item, [...path], stdValue)) {
          targetsArr.push(item);
        }
        targetPath.pop();
        if (targetsArr.length > 0) {
          if (targetsArr.length === 1) {
            targetArr.push(targetsArr[0]);
          } else {
            targetArr.push(targetsArr);
          }
        }
      }
    }
    return findTargetOnlyOne(data[key], path, stdValue);
  } catch (error) {
    targetPath.pop();
    return `Unknown Error`;
  }
}

function cleanPath(path, comparePath) {
  path = path.split(".");
  while (path[0] && comparePath[0] && path[0] === comparePath[0]) {
    path.shift();
    comparePath.shift();
  }
  return path;
}

function formatJSONOnlyOne(data, path) {
  key = path.shift();
  if (key === undefined) return data;
  try {
    if (data[key] === undefined) {
      return path.length ? `Invalid Key : ${key}` : undefined;
    }
    if (data[key] instanceof Array) {
      const valArray = [];
      for (item of data[key]) {
        valArray.push(formatJSONOnlyOne(item, [...path]));
      }
      return valArray;
    }
    return formatJSONOnlyOne(data[key], path);
  } catch (error) {
    return `Unknown Error`;
  }
}

let input = {
  data: json,
  stdPath: "response.body.items.stationName",
  stdValue: "중구",
  outputPaths: [
    "response.body.items.khaiValue",
    "response.body.items.so2Value",
    "response.body.items.coValue",
  ],
};

let targetArr = [];
let targetPath = [];
findTarget(input);

const cleanedOutputPaths = input.outputPaths.map((path) =>
  cleanPath(path, [...targetPath])
);

let result = [];
targetArr.forEach((target) => {
  let ret = [];
  cleanedOutputPaths.forEach((path) => {
    if (path.length) {
      const newTarget = JSON.parse(JSON.stringify(target));
      ret.push(formatJSONOnlyOne(newTarget, [...path]));
    } else {
      ret.push(
        "Invalid Path Error: The outputPath must be a sibling or child path of targetPath"
      );
    }
  });
  result.push(ret);
});

if (result.length === 1) {
  result = result[0];
}
console.log(result);
